{
  "lastUpdated": "2026-05-21T03:30:00Z",
  "events": [
    {
      "id": "oef-basrah",
      "title": "Second wave of US sanctions: 19 vessels designated for deceptive shipping",
      "location": "Basrah, Iraq",
      "lat": 30.5081, "lng": 47.7833,
      "date": "2026-05-19", "dateLabel": "19 May 2026",
      "category": "policy", "severity": "medium",
      "description": "US designated 19 more vessels in second wave of Operation Economic Fury, targeting ships using deceptive shipping practices to obfuscate Iran port calls. SAR imagery showed 9 vessels manipulating positions at Basrah Oil Terminal. Builds on first wave (9 vessels, 15 April).",
      "sourceUrl": "https://insights.windward.ai/",
      "sourceLabel": "Windward (MIOC)",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "cma-cgm-san-antonio",
      "title": "CMA CGM San Antonio attacked in Hormuz",
      "location": "Strait of Hormuz",
      "lat": 26.2, "lng": 56.6,
      "date": "2026-05-05", "dateLabel": "Early May 2026",
      "category": "vessel", "severity": "high",
      "description": "French container line CMA CGM confirmed its vessel San Antonio was attacked while transiting the Strait of Hormuz. One of several merchant-vessel attacks during the wider crisis; 17 ships damaged, 7 abandoned across the crisis.",
      "sourceUrl": "https://carraglobe.com/strait-of-hormuz-closure-2026/",
      "sourceLabel": "Carra Globe",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "us-east-coast-strike",
      "title": "US East Coast ports — dockworker strike risk",
      "location": "New York / New Jersey",
      "lat": 40.7128, "lng": -74.0060,
      "date": "2026-05-01", "dateLabel": "May 2026",
      "category": "labour", "severity": "medium",
      "description": "Tens of thousands of ILA dockworkers threatening strike if union cannot reach a deal to renew its contract with terminal operators. Could shut down major US East Coast ports as early as next week.",
      "sourceUrl": "https://www.cbsnews.com/tag/supply-chain/",
      "sourceLabel": "CBS News",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "dhl-tipping-point",
      "title": "DHL CEO warns Gulf shock approaches \"tipping point\"",
      "location": "Bonn, Germany",
      "lat": 50.7374, "lng": 7.0982,
      "date": "2026-04-21", "dateLabel": "21 Apr 2026",
      "category": "industry", "severity": "info",
      "description": "DHL Group CEO Tobias Meyer warned that sustained disruption in Gulf crude flows could push the global economy toward a tipping point. Routes tightening, freight markets constrained, shipping rates rising — especially on Asia-Europe lanes.",
      "sourceUrl": "https://logisticsviewpoints.com/2026/04/24/supply-chain-and-logistics-news-april-20th-23rd-2026/",
      "sourceLabel": "Logistics Viewpoints",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "mexico-blockades",
      "title": "Farmer-trucker blockades disrupt Mexican ports & highways",
      "location": "Central Mexico",
      "lat": 19.4326, "lng": -99.1332,
      "date": "2026-04-20", "dateLabel": "Apr 2026",
      "category": "labour", "severity": "medium",
      "description": "Major farmer-trucker blockades across Mexico are disrupting highways, slowing port and border operations, and forcing logistics providers to reroute freight. Affecting both export and import flows through Mexican ports.",
      "sourceUrl": "https://www.freightwaves.com/news/category/news/business/supply-chains",
      "sourceLabel": "FreightWaves",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "ups-surge-fee",
      "title": "UPS Surge Emergency Fee in effect",
      "location": "United States",
      "lat": 33.7490, "lng": -84.3880,
      "date": "2026-04-19", "dateLabel": "Since 19 Apr 2026",
      "category": "policy", "severity": "medium",
      "description": "UPS implemented a Surge Emergency Fee. Most international shipments incur a $0.23/lb charge; China and Hong Kong → US shipments face $0.32/lb. Applies to premium services (Worldwide Express, Express Freight).",
      "sourceUrl": "https://logisticsviewpoints.com/2026/04/24/supply-chain-and-logistics-news-april-20th-23rd-2026/",
      "sourceLabel": "Logistics Viewpoints",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "manzanillo-cjng",
      "title": "Port of Manzanillo destabilised by CJNG cartel violence",
      "location": "Manzanillo, Mexico",
      "lat": 19.05, "lng": -104.32,
      "date": "2026-04-15", "dateLabel": "Apr 2026",
      "category": "conflict", "severity": "high",
      "description": "Death of CJNG cartel leader \"El Mencho\" triggered violent retaliation across western Mexico — disrupting highways, rattling the Port of Manzanillo (Mexico's busiest Pacific port), and threatening US-Mexico cross-border trade flows.",
      "sourceUrl": "https://www.freightwaves.com/news/category/news/business/supply-chains",
      "sourceLabel": "FreightWaves",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "russia-lng-cape",
      "title": "Russian LNG carriers rerouting via Cape of Good Hope",
      "location": "Cape of Good Hope",
      "lat": -34.3568, "lng": 18.4737,
      "date": "2026-04-01", "dateLabel": "Apr–May 2026",
      "category": "route", "severity": "info",
      "description": "Five Russia-flagged LNG carriers tracked sailing from Arctic ports to South China Sea via Cape of Good Hope and Sunda Strait throughout April–May, following the Arctic Metagaz drone strike. Tactic spreading beyond the LNG segment.",
      "sourceUrl": "https://insights.windward.ai/",
      "sourceLabel": "Windward (MIOC)",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "us-10pct-tariff",
      "title": "US imposes 10% global tariff after Supreme Court ruling",
      "location": "Washington, D.C.",
      "lat": 38.9072, "lng": -77.0369,
      "date": "2026-04-01", "dateLabel": "Apr 2026",
      "category": "policy", "severity": "medium",
      "description": "Trump unveiled a new 10% global tariff after the Supreme Court ruled many of his earlier country-specific tariffs unconstitutional. Companies advised to track entries, file protests, and prepare for billions-of-dollars refund process.",
      "sourceUrl": "https://www.freightwaves.com/news/category/news/business/supply-chains",
      "sourceLabel": "FreightWaves",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "jnpt-surge",
      "title": "Jawaharlal Nehru Port: transhipment volume up 700%",
      "location": "Nhava Sheva, India",
      "lat": 18.9456, "lng": 72.9544,
      "date": "2026-03-15", "dateLabel": "Mar–May 2026",
      "category": "route", "severity": "info",
      "description": "India's Jawaharlal Nehru Port has rapidly transformed into a major transhipment hub, with volumes up more than 700% from February baselines. Saudi Arabia and Singapore are also emerging as Gulf-diversion destinations.",
      "sourceUrl": "https://www.freightwaves.com/news/34000-shipping-routes-diverted-from-hormuz-disruption-report",
      "sourceLabel": "FreightWaves / project44",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "arctic-metagaz",
      "title": "Russian LNG carrier Arctic Metagaz hit by drone strike",
      "location": "East of Malta",
      "lat": 35.9, "lng": 15.0,
      "date": "2026-03-04", "dateLabel": "4 Mar 2026",
      "category": "vessel", "severity": "high",
      "description": "The laden LNG carrier Arctic Metagaz was struck by a drone east of Malta. Crew abandoned ship; vessel later anchored off Benghazi after EU-sanctioned salvage. Triggered Russia LNG carriers avoiding Mediterranean transits.",
      "sourceUrl": "https://insights.windward.ai/",
      "sourceLabel": "Windward (MIOC)",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "red-sea-houthis",
      "title": "Red Sea attacks resume — Bab el-Mandeb transits halved",
      "location": "Bab el-Mandeb strait",
      "lat": 12.5833, "lng": 43.3333,
      "date": "2026-03-01", "dateLabel": "Since Mar 2026",
      "category": "chokepoint", "severity": "high",
      "description": "Houthis resumed attacks on Red Sea shipping after the October 2025 ceasefire collapsed. Bab el-Mandeb transits stuck at ~50% pre-attack levels. Carriers default to Cape of Good Hope routing — adding 10-14 days Asia <-> Europe.",
      "sourceUrl": "https://www.imf.org/en/blogs/articles/2026/04/29/global-disruptions-are-testing-how-the-world-moves-goods-and-people",
      "sourceLabel": "IMF · International Crisis Group",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "hormuz-crisis",
      "title": "Strait of Hormuz crisis — 1,550+ vessels stranded",
      "location": "Strait of Hormuz",
      "lat": 26.5667, "lng": 56.2500,
      "date": "2026-02-28", "dateLabel": "Since 28 Feb 2026 · ongoing",
      "category": "chokepoint", "severity": "critical",
      "description": "Iran has largely blocked Strait of Hormuz shipping since US-Israel struck Iranian targets on 28 Feb. As of early May: 22,500 mariners trapped on 1,550+ vessels; traffic ~5-15% of pre-war volume. US naval blockade since 13 April. Iran allowing limited transit via northern coastal corridor under IRGC monitoring.",
      "sourceUrl": "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis",
      "sourceLabel": "Wikipedia · Carra Globe · Al Jazeera",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "tema-cranes",
      "title": "Port of Tema operating with crane outages",
      "location": "Tema, Ghana",
      "lat": 5.6739, "lng": 0.0228,
      "date": "2026-02-15", "dateLabel": "Since Feb 2026",
      "category": "port", "severity": "medium",
      "description": "Tema port experiencing significant crane outages. Berthing delays for window vessels extend up to 36 hours; non-window vessels subject to berth availability. Operating under strict pro-forma move limits.",
      "sourceUrl": "https://mykn.kuehne-nagel.com/news/article/port-operational-updates-from-19-02-2026",
      "sourceLabel": "Kuehne+Nagel port updates",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "mombasa-congestion",
      "title": "Port of Mombasa: 5+ day waits, equipment shortages",
      "location": "Mombasa, Kenya",
      "lat": -4.0435, "lng": 39.6682,
      "date": "2026-02-01", "dateLabel": "Since Feb 2026",
      "category": "port", "severity": "medium",
      "description": "Mombasa terminal experiencing prolonged congestion and reduced productivity due to equipment shortages and high transhipment volumes diverted from Gulf. 7-day average vessel wait time around 5+ days.",
      "sourceUrl": "https://mykn.kuehne-nagel.com/news/article/port-operational-updates-from-19-02-2026",
      "sourceLabel": "Kuehne+Nagel port updates",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "karachi-fire",
      "title": "Container terminal fire at Port of Karachi",
      "location": "Karachi, Pakistan",
      "lat": 24.8607, "lng": 67.0011,
      "date": "2026-01-16", "dateLabel": "16 Jan 2026",
      "category": "port", "severity": "medium",
      "description": "Fire in the container terminals disrupted operations on 16 January. Over 20 containers were impacted; the fire forced suspension of handling operations for two vessels.",
      "sourceUrl": "https://www.everstream.ai/risk-centers/port-congestion-report-22-january-2026/",
      "sourceLabel": "Everstream Analytics",
      "added": "2026-05-21T03:30:00Z"
    },
    {
      "id": "panama-drought",
      "title": "Panama Canal — drought-induced transit limits ongoing",
      "location": "Panama Canal",
      "lat": 9.0833, "lng": -79.6833,
      "date": "2026-01-01", "dateLabel": "Ongoing 2026",
      "category": "chokepoint", "severity": "medium",
      "description": "Dwindling water levels in Panama Canal continue to constrain global supply chains. Compounds the Suez & Hormuz disruptions — with East Coast US <-> Asia traffic looking for any working alternative.",
      "sourceUrl": "https://unctad.org/news/unprecedented-shipping-disruptions-raise-risk-global-trade-unctad-warns",
      "sourceLabel": "UNCTAD",
      "added": "2026-05-21T03:30:00Z"
    }
  ]
}
